name: WebSocket Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'package.json'
      - '.github/workflows/websocket-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    services:
      ssh-server:
        image: ghcr.io/billchurch/ssh_test:alpine
        ports:
          - 4444:22
        env:
          SSH_USER: testuser
          SSH_PASSWORD: testpassword
        options: >-
          --health-cmd "nc -z localhost 22"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Checkout client repository
      uses: actions/checkout@v4
      with:
        repository: billchurch/webssh2_client
        path: ../webssh2_client
    
    - name: Install client dependencies
      working-directory: ../webssh2_client
      run: npm ci
    
    - name: Build client with WebSocket
      working-directory: ../webssh2_client
      run: VITE_USE_WEBSOCKET=true npm run build
    
    - name: Link client to server
      run: npm link ../webssh2_client
    
    - name: Run unit tests
      run: npm test
    
    - name: Run WebSocket authentication tests
      run: npm run test:playwright:auth
      env:
        USE_WEBSOCKET: true
        NODE_ENV: test
    
    - name: Run WebSocket performance tests
      run: npm run test:playwright:perf
      env:
        USE_WEBSOCKET: true
        NODE_ENV: test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test videos
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-videos-${{ matrix.node-version }}
        path: test-results/
        retention-days: 7